# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-toml
    - id: debug-statements

- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black
      language_version: python3
      args: [--line-length=88]

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      additional_dependencies: [
        'flake8-docstrings',
        'flake8-quotes',
        'flake8-bugbear'
      ]
      args: [
        "--max-line-length=88",
        "--extend-ignore=E203,W503,Q000,D100",
        "--exclude=.git,__pycache__,build,dist,*.egg-info,fraud_detection/main.py",
      ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.0
  hooks:
    - id: mypy
      args: [
        "--ignore-missing-imports",
        "--disallow-untyped-defs",
        "--check-untyped-defs"
      ]
