# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-toml
    - id: debug-statements

- repo: local
  hooks:
      - id: local-pipeline
        name: Run Local Lint
        entry: ./hooks/run_pipeline.sh
        args: ["-s", "lint"]  # Only run lint by default
        language: system
        pass_filenames: false
        stages: [push]
